# Generated by Django 5.1.1 on 2024-12-26 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_addchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addchapter',
            name='Course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='course_chapter', to='MAIN.course'),
        ),
    ]
