# Generated by Django 5.1.1 on 2024-12-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_studentcourseenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveBigIntegerField(default=0)),
                ('review', models.PositiveBigIntegerField(default=0)),
                ('reviw_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.student')),
            ],
        ),
    ]
