# Generated by Django 5.1.1 on 2024-12-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_courserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserating',
            name='review',
            field=models.TextField(default=0),
        ),
    ]
